#!/usr/bin/env bash
# save_lab_map.sh — post-mapping artefact collection.
#
# Run AFTER stopping mapping_only.launch.py. Copies the PCD generated by
# FAST-LIO2 (pcd_save_en=true in hesai_xt16.yaml) to a timestamped folder
# under maps/, then optionally extracts a 2D occupancy grid via octomap CLI
# (offline, decoupled from the live octomap_server node).
#
# Usage:  ./scripts/save_lab_map.sh [output_name]

set -euo pipefail

WS_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NAME="${1:-lab_$(date +%Y%m%d_%H%M%S)}"
OUT_DIR="${WS_ROOT}/maps/${NAME}"

# FAST-LIO2 writes hesai_xt16_map.pcd in the working dir of fastlio_mapping.
# When launched via the bringup scripts that working dir is the user's
# HOME/.ros directory by default (or the directory from which ros2 launch
# was invoked). Search both.
CANDIDATES=(
    "${HOME}/.ros/hesai_xt16_map.pcd"
    "${WS_ROOT}/hesai_xt16_map.pcd"
    "/root/.ros/hesai_xt16_map.pcd"
    "/workspaces/go2_ws/hesai_xt16_map.pcd"
)

PCD=""
for c in "${CANDIDATES[@]}"; do
    [[ -f "$c" ]] && PCD="$c" && break
done

if [[ -z "$PCD" ]]; then
    echo "PCD not found. Searched:" >&2
    printf '  %s\n' "${CANDIDATES[@]}" >&2
    exit 1
fi

mkdir -p "$OUT_DIR"
cp "$PCD" "${OUT_DIR}/cloud.pcd"
echo "Saved: ${OUT_DIR}/cloud.pcd ($(du -h "$PCD" | cut -f1))"

# Optional: convert to 2D occupancy grid (.bt + .png) via octomap CLI tools.
if command -v octomap_server >/dev/null && command -v binvox2bt >/dev/null; then
    echo "octomap CLI present — generating .bt and .png projection"
    # Placeholder: real conversion depends on which octomap CLI is shipped.
    # Customise once the deployment image's octomap version is fixed.
fi

echo "Done. Map artefacts in: ${OUT_DIR}"
